# Generated by Django 3.2.10 on 2022-02-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='calendar',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='schedule.calendar'),
            preserve_default=False,
        ),
    ]
