# Generated by Django 3.2.10 on 2022-03-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='meeting_location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='club',
            name='meeting_type',
            field=models.CharField(choices=[('ONL', 'Online'), ('INP', 'In-person')], default='INP', max_length=3),
        ),
    ]
