# Generated by Django 3.2.10 on 2022-02-21 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20220219_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owner', through='clubs.OwnerMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
