# Generated by Django 3.2.10 on 2022-02-06 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20220203_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberMembership',
            new_name='Membership',
        ),
        migrations.CreateModel(
            name='Club_Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.book')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='book', through='clubs.Club_Books', to='clubs.Book'),
        ),
    ]
