# Generated by Django 3.2.10 on 2022-02-06 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20220206_2126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership',
            new_name='Club_Users',
        ),
        migrations.AlterField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(blank=b'I00\n', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
