# Generated by Django 3.2.10 on 2022-03-01 12:01

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('clubs', '0003_auto_20220301_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='club',
            name='meeting_location',
        ),
        migrations.CreateModel(
            name='MeetingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_link', models.URLField(blank=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.event')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Full name')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.event')),
            ],
            options={
                'verbose_name': 'Meeting Address',
            },
        ),
    ]
