# Generated by Django 3.2.10 on 2022-02-06 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20220206_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_users',
            name='num',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
