# Generated by Django 3.2.10 on 2022-03-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_meetingaddress_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingaddress',
            name='address2',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address line 2'),
        ),
    ]
