# Generated by Django 3.2.10 on 2022-03-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_meetinglink_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_small',
            field=models.ImageField(default='https://media2.fdncms.com/stranger/imager/u/large/43820816/1591119073-screen_shot_2020-06-02_at_10.30.13_am.png', upload_to=''),
        ),
    ]
