# Generated by Django 3.2.10 on 2022-02-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20220207_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='id',
        ),
    ]
