# Generated by Django 3.2.10 on 2022-02-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_rename_userid_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='userId',
        ),
    ]
