# Generated by Django 3.2.10 on 2022-03-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_auto_20220303_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_large',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_medium',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_small',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
