# Generated by Django 3.2.10 on 2022-03-08 18:20

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_user_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Full name')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=1024, verbose_name='Address line 2')),
                ('zip_code', models.CharField(blank=True, max_length=12, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='meetingaddress',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='meetingaddress',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='meetingaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='meetingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='meetingaddress',
            name='name',
        ),
        migrations.RemoveField(
            model_name='meetingaddress',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='meetingaddress',
            name='address',
            field=models.ForeignKey(blank=b'I00\n', default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.address'),
            preserve_default=False,
        ),
    ]
