# Generated by Django 3.2.10 on 2022-02-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_user_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='id',
        ),
    ]
