# Generated by Django 3.2.10 on 2022-03-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_auto_20220303_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_large',
            field=models.ImageField(default='http://images.amazon.com/images/P/0747256470.01.LZZZZZZZ.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_medium',
            field=models.ImageField(default='http://images.amazon.com/images/P/0747256470.01.LZZZZZZZ.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_small',
            field=models.ImageField(default='http://images.amazon.com/images/P/0747256470.01.LZZZZZZZ.jpg', upload_to=''),
        ),
    ]
