# Generated by Django 3.2.10 on 2022-03-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_user_followers'),
        ('clubs', '0012_auto_20220303_2017'),
    ]

    operations = [
    ]
