# Generated by Django 3.2.10 on 2022-02-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_auto_20220207_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club_books',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='club_books',
            old_name='club',
            new_name='club_id',
        ),
        migrations.RenameField(
            model_name='club_users',
            old_name='club',
            new_name='club_id',
        ),
        migrations.RenameField(
            model_name='club_users',
            old_name='user',
            new_name='user_id',
        ),
    ]
