# Generated by Django 3.2.10 on 2022-02-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_auto_20220207_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club_users',
            old_name='num',
            new_name='role',
        ),
    ]
