# Generated by Django 3.2.10 on 2022-02-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_rename_num_club_users_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club_users',
            old_name='role',
            new_name='role_num',
        ),
    ]
