# Generated by Django 3.2.10 on 2022-03-10 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
