<<<<<<< HEAD
# Generated by Django 3.2.10 on 2022-03-10 17:18
=======

# Generated by Django 3.2.10 on 2022-03-10 19:57

>>>>>>> d4f583260ead71c9c5608da01f05e06a3bee5369

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_auto_20220308_1820'),
        ('clubs', '0016_remove_book_rating'),
    ]

    operations = [
    ]
