# Generated by Django 3.2.10 on 2022-03-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_merge_0010_auto_20220308_1820_0016_remove_book_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club_books',
            options={'verbose_name': 'Club Book'},
        ),
        migrations.AlterModelOptions(
            name='club_users',
            options={'verbose_name': 'Club User'},
        ),
    ]
