# Generated by Django 3.2.10 on 2022-03-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_auto_20220312_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_rating',
            name='rating',
            field=models.CharField(choices=[('Rate book', 'Rate book'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='Rate book', max_length=9),
        ),
    ]
