# Generated by Django 3.2.10 on 2022-03-17 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_alter_book_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_Book_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clubs.book')),
                ('club', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'verbose_name': 'Club Book History',
            },
        ),
    ]
