# Generated by Django 3.2.10 on 2022-03-20 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_club_book_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_book_history',
            name='average_rating',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
