# Generated by Django 3.2.10 on 2022-03-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0021_club_book_history_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownermembership',
            name='club',
        ),
        migrations.RemoveField(
            model_name='ownermembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='club',
            name='applicants',
        ),
        migrations.RemoveField(
            model_name='club',
            name='members',
        ),
        migrations.RemoveField(
            model_name='club',
            name='owners',
        ),
        migrations.DeleteModel(
            name='ApplicantMembership',
        ),
        migrations.DeleteModel(
            name='OwnerMembership',
        ),
    ]
