# Generated by Django 3.2.10 on 2022-03-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0023_alter_club_users_role_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='books',
        ),
        migrations.AlterField(
            model_name='club_users',
            name='role_num',
            field=models.CharField(choices=[('1', 'Applicant'), ('2', 'Member'), ('3', 'Officer'), ('4', 'Owner')], default=1, max_length=1),
        ),
    ]
