# Generated by Django 3.2.10 on 2022-03-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0025_user_book_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='book_rating',
            options={'verbose_name': 'User Book Rating', 'verbose_name_plural': 'User Book Ratings'},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name'], 'verbose_name': 'Club', 'verbose_name_plural': 'Clubs'},
        ),
        migrations.AlterModelOptions(
            name='club_book_history',
            options={'verbose_name': 'Club Book History', 'verbose_name_plural': 'Club Book Histories'},
        ),
        migrations.AlterModelOptions(
            name='club_books',
            options={'verbose_name': 'Club Favourite Book', 'verbose_name_plural': 'Club Favourite Books'},
        ),
        migrations.AlterModelOptions(
            name='club_users',
            options={'verbose_name': 'Club', 'verbose_name_plural': 'Club User'},
        ),
        migrations.AlterModelOptions(
            name='meetingaddress',
            options={'verbose_name': 'Meeting Address', 'verbose_name_plural': 'Meeting Addresses'},
        ),
        migrations.AlterModelOptions(
            name='meetinglink',
            options={'verbose_name': 'Meeting Link', 'verbose_name_plural': 'Meeting Links'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='user_book_history',
            options={'verbose_name': 'User Book History', 'verbose_name_plural': 'User Book Histories'},
        ),
        migrations.AlterModelOptions(
            name='user_books',
            options={'verbose_name': 'User Favourite Book', 'verbose_name_plural': 'User Favourite Books'},
        ),
        migrations.AlterField(
            model_name='book_rating',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=9),
        ),
    ]
