# Generated by Django 3.2.10 on 2022-04-05 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0025_user_book_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='book_rating',
            options={'verbose_name': 'User Book Rating', 'verbose_name_plural': 'User Book Ratings'},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name'], 'verbose_name': 'Club', 'verbose_name_plural': 'Clubs'},
        ),
        migrations.AlterModelOptions(
            name='club_book_history',
            options={'verbose_name': 'Club Book History', 'verbose_name_plural': 'Club Book Histories'},
        ),
        migrations.AlterModelOptions(
            name='club_books',
            options={'verbose_name': 'Club Favourite Book', 'verbose_name_plural': 'Club Favourite Books'},
        ),
        migrations.AlterModelOptions(
            name='club_users',
            options={'verbose_name': 'Club', 'verbose_name_plural': 'Club User'},
        ),
        migrations.AlterModelOptions(
            name='meetingaddress',
            options={'verbose_name': 'Meeting Address', 'verbose_name_plural': 'Meeting Addresses'},
        ),
        migrations.AlterModelOptions(
            name='meetinglink',
            options={'verbose_name': 'Meeting Link', 'verbose_name_plural': 'Meeting Links'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='user_book_history',
            options={'verbose_name': 'User Book History', 'verbose_name_plural': 'User Book Histories'},
        ),
        migrations.AlterModelOptions(
            name='user_books',
            options={'verbose_name': 'User Favourite Book', 'verbose_name_plural': 'User Favourite Books'},
        ),
        migrations.AlterField(
            model_name='book_rating',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=9),
        ),
        migrations.AlterField(
            model_name='club_users',
            name='role_num',
            field=models.CharField(choices=[('1', 'Applicant'), ('2', 'Member'), ('4', 'Owner')], default=1, max_length=1),
        ),
        migrations.CreateModel(
            name='UserClubRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Club Recommendation',
                'verbose_name_plural': 'User Club Recommendations',
            },
        ),
        migrations.CreateModel(
            name='UserBookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Book Recommendation',
                'verbose_name_plural': 'User Book Recommendations',
            },
        ),
        migrations.CreateModel(
            name='User_Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Recommended Club',
                'verbose_name_plural': 'User Recommended Clubs',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='clubs.post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='clubs.post')),
            ],
            options={
                'verbose_name': 'Post Comment',
                'verbose_name_plural': 'Post Comments',
            },
        ),
        migrations.CreateModel(
            name='ClubFeedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.post')),
            ],
            options={
                'verbose_name': 'Club Feed Post',
                'verbose_name_plural': 'Club Feed Posts',
            },
        ),
        migrations.CreateModel(
            name='ClubBookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.book')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'verbose_name': 'Club Book Recommendation',
                'verbose_name_plural': 'Club Book Recommendations',
            },
        ),
    ]
