# Generated by Django 3.2.10 on 2022-03-27 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_auto_20220325_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubFeed',
            fields=[
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clubs.club')),
                ('posts', models.ManyToManyField(to='clubs.Post')),
            ],
        ),
    ]
