# Generated by Django 3.2.10 on 2022-03-27 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_auto_20220325_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubFeedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.post')),
            ],
        ),
    ]
