# Generated by Django 3.2.10 on 2022-04-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_auto_20220327_1438'),
        ('clubs', '0027_clubfeedpost'),
    ]

    operations = [
    ]
