# Generated by Django 3.2.10 on 2022-04-05 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0028_merge_0026_auto_20220327_1438_0027_clubfeedpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubfeedpost',
            options={'verbose_name': 'Club Feed Post', 'verbose_name_plural': 'Club Feed Posts'},
        ),
        migrations.AlterField(
            model_name='club_users',
            name='role_num',
            field=models.CharField(choices=[('1', 'Applicant'), ('2', 'Member'), ('4', 'Owner')], default=1, max_length=1),
        ),
        migrations.CreateModel(
            name='UserClubRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Club Recommendation',
                'verbose_name_plural': 'User Club Recommendations',
            },
        ),
        migrations.CreateModel(
            name='UserBookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Book Recommendation',
                'verbose_name_plural': 'User Book Recommendations',
            },
        ),
        migrations.CreateModel(
            name='User_Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Recommended Club',
                'verbose_name_plural': 'User Recommended Clubs',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='clubs.post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='clubs.post')),
            ],
            options={
                'verbose_name': 'Post Comment',
                'verbose_name_plural': 'Post Comments',
            },
        ),
        migrations.CreateModel(
            name='ClubBookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.book')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
            options={
                'verbose_name': 'Club Book Recommendation',
                'verbose_name_plural': 'Club Book Recommendations',
            },
        ),
    ]
