# Generated by Django 3.2.10 on 2022-04-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_auto_20220405_1433'),
        ('clubs', '0028_merge_0026_auto_20220327_1438_0027_clubfeedpost'),
    ]

    operations = [
    ]
