# Generated by Django 3.2.10 on 2022-03-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0028_merge_0026_auto_20220327_1438_0027_clubfeedpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubfeedpost',
            options={'verbose_name': 'Club Feed Post', 'verbose_name_plural': 'Club Feed Posts'},
        ),
    ]
