# Generated by Django 3.2.10 on 2022-03-29 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0029_alter_clubfeedpost_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Recommended Club',
                'verbose_name_plural': 'User Recommended Clubs',
            },
        ),
    ]
