# Generated by Django 3.2.10 on 2022-03-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0027_user_clubs'),
        ('clubs', '0029_alter_clubfeedpost_options'),
    ]

    operations = [
    ]
