# Generated by Django 3.2.10 on 2022-03-29 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0030_merge_0027_user_clubs_0029_alter_clubfeedpost_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='clubs.post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='clubs.post')),
            ],
            options={
                'verbose_name': 'Post Comment Post',
                'verbose_name_plural': 'Post Comment Post',
            },
        ),
    ]
