# Generated by Django 3.2.10 on 2022-03-29 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0031_postcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'verbose_name': 'Post Comment', 'verbose_name_plural': 'Post Comments'},
        ),
    ]
