# Generated by Django 3.2.10 on 2022-04-04 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0035_alter_club_users_role_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClubRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Club Recommendation',
                'verbose_name_plural': 'User Club Recommendations',
            },
        ),
    ]
